Fitness/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fitness.Models
{
    public class Recipe
    {
        public int ID { get; set; }

        [StringLength(100, MinimumLength = 3)]
        public string Title { get; set; }

//        public List<String> Photos { get; set; }

        public String Ingredients { get; set; }

        public String Directions { get; set; }

    }
}

Fitness/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fitness.Models;
using Fitness.Service;
using System.Data.Entity.Infrastructure;

namespace Fitness.Controllers
{
    public class RecipeController : Controller
    {

        public IRecipeService RecipeService { get; set; }

        public RecipeController()
        {
            RecipeService = new RecipeService();
        }

        // GET: /Recipe/5
        // Note: If you request /Recipe (with no ID), it will return an error.
        public ActionResult Index(int? recipeID)
        {
            if (recipeID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // If we get to this point, we have a Recipe ID that is an integer
            Recipe foundRecipe = RecipeService.FindRecipeByID(recipeID.GetValueOrDefault()); 

            // We did not find the Recipe by ID.  Return an error
            if (foundRecipe == null)
            {
                return HttpNotFound();
            }
            // We did find the Recipe.  Render it in the View.
            else
            {
                return View(foundRecipe);    
            }            
        }

        // List
        public ActionResult List()
        {
            IList<Recipe> allRecipes = RecipeService.FindAllRecipes(); 

            return View(allRecipes);
        }


        // GET: /Recipe/Create
        public ActionResult Create()
        {
        
            return View();
        }

       
    }
}

Fitness/Views/Recipe/Create.cshtml
@model Fitness.Models.Recipe

@{
    ViewBag.Title = "Create";
}

<h2>Create New Recipe</h2>


<form action="/Recipe/Create" method="POST" role="form">
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="recipeTitleInputField">Title</label>
        <input type="email" class="form-control" id="recipeTitleInputField" placeholder="Enter Recipe Title">
    </div>
    <div class="form-group">
        <label for="ingredientsTextArea">Ingredients</label>
        <textarea class="form-control" id="ingredientsTextArea" placeholder="Recipe Ingredients"></textarea>
    </div>
    <div class="form-group">
        <label for="directionsTextArea">Directions</label>
        <textarea class="form-control" id="directionsTextArea" placeholder="Recipe Directions"></textarea>
    </div>
    <button type="submit" class="btn btn-default">Save Recipe</button>

</form>

Fitness/Views/Recipe/Delete.cshtml
@model Fitness.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Department
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseID)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Fitness/Views/Recipe/Details.cshtml
@model Fitness.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CourseID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Fitness/Views/Recipe/Edit.cshtml
@model Fitness.Models.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.CourseID)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.CourseID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credits, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credits)
                @Html.ValidationMessageFor(model => model.Credits)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentID, "DepartmentID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentID", String.Empty)
                @Html.ValidationMessageFor(model => model.DepartmentID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Fitness/Views/Recipe/Index.cshtml
@model Fitness.Models.Recipe

@{
    ViewBag.Title = "Recipes";
}

<h2>Recipe</h2>

<p>
    @Html.ActionLink("Create New Recipe", "Create")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Directions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ingredients)
        </th>
    </tr>
    <tr>
        <td>
           @Html.DisplayFor(model => model.Title)
        </td>
        <td>
           @Html.DisplayFor(model => model.Directions)
        </td>
        <td>
           @Html.DisplayFor(model => model.Ingredients)
        </td>
    </tr>
    

</table>

Fitness/Views/Recipe/List.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<Fitness.Models.Recipe>

@{
    ViewBag.Title = "Recipe List";
}

<h2>Recipe List</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ingredients)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Directions)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingredients)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Directions)
            </td>
        </tr>
    }
  
</table>

<input type="button" class="btn btn-primary" value="Add New Recipe" onclick="location.href='@Url.Action("Create", "Recipe")'" />
    

Fitness/Views/Recipe/UpdateCourseCredits.cshtml
@model Fitness.Models.Course

@{
    ViewBag.Title = "UpdateCourseCredits";
}

<h2>Update Course Credits</h2>

@if (ViewBag.RowsAffected == null)
{
    using (Html.BeginForm())
    {
        <p>
            Enter a number to multiply every course's credits by: @Html.TextBox("multiplier")
        </p>
        <p>
            <input type="submit" value="Update" />
        </p>
    }
}
@if (ViewBag.RowsAffected != null)
{
    <p>
        Number of rows updated: @ViewBag.RowsAffected
    </p>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>